"use client"

import Link from "next/link"
import { Activity, AlertTriangle } from "lucide-react"

import { useLangStore } from "@/lib/store"
import { useBackendStore } from "@/lib/use-backend-status"

const TEXT = {
  vi: {
    tagline: "Phân tích thị trường bằng AI",
    disclaimerTitle: "Miễn trừ trách nhiệm",
    disclaimer:
      "ForecastAI là đồ án học thuật. Mọi dự báo do mô hình AI sinh ra và có thể sai. Toàn bộ giao dịch trên hệ thống là mô phỏng, không sử dụng tiền thật. Nội dung tại đây không phải lời khuyên đầu tư, tài chính hay pháp lý.",
    status: { online: "Máy chủ hoạt động", offline: "Mất kết nối máy chủ", checking: "Đang kiểm tra…", "not-configured": "Chưa cấu hình máy chủ" },
    nav: { markets: "Thị trường", forecast: "Dự báo", research: "Nghiên cứu", portfolio: "Danh mục", autoTrade: "Giao dịch tự động" },
  },
  en: {
    tagline: "AI-Powered Market Intelligence",
    disclaimerTitle: "Disclaimer",
    disclaimer:
      "ForecastAI is an academic project. All forecasts are generated by AI models and may be wrong. Every trade on this system is simulated with no real money. Nothing here is investment, financial, or legal advice.",
    status: { online: "Server online", offline: "Server unreachable", checking: "Checking…", "not-configured": "Server not configured" },
    nav: { markets: "Markets", forecast: "Forecast", research: "Research", portfolio: "Portfolio", autoTrade: "Auto Trade" },
  },
} as const

const STATUS_COLOR = {
  online: "bg-positive",
  offline: "bg-negative",
  checking: "bg-muted-foreground",
  "not-configured": "bg-warning",
} as const

export function Footer() {
  const lang = useLangStore((s) => s.lang)
  const status = useBackendStore((s) => s.status)
  const t = TEXT[lang] ?? TEXT.vi

  return (
    <footer className="mt-12 border-t border-border bg-bg-secondary" data-print-hide>
      <div className="mx-auto max-w-[1600px] px-4 py-8 lg:px-6">
        {/* ── Miễn trừ trách nhiệm ────────────────────────────────────────────
            Đặt lên đầu footer và trình bày như một khối riêng có viền.
            Ở bản trước đây là một dòng chữ xám nhỏ lẫn giữa các liên kết,
            gần như không ai đọc. */}
        <div className="mb-8 flex items-start gap-3 rounded-lg border border-warning/25 bg-warning/5 p-4">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-warning" aria-hidden />
          <div>
            <p className="text-sm font-semibold text-card-foreground">{t.disclaimerTitle}</p>
            <p className="mt-1 max-w-3xl text-sm leading-relaxed text-muted-foreground">
              {t.disclaimer}
            </p>
          </div>
        </div>

        <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-md bg-primary">
              <Activity className="h-4 w-4 text-primary-foreground" strokeWidth={2.5} aria-hidden />
            </div>
            <span className="font-bold text-foreground">
              Forecast<span className="text-primary">AI</span>
            </span>
            <span className="ml-2 hidden text-sm text-muted-foreground sm:inline">{t.tagline}</span>
          </div>

          <nav className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground">
            <Link href="/markets" className="transition-colors hover:text-foreground">{t.nav.markets}</Link>
            <Link href="/forecast" className="transition-colors hover:text-foreground">{t.nav.forecast}</Link>
            <Link href="/research" className="transition-colors hover:text-foreground">{t.nav.research}</Link>
            <Link href="/portfolio" className="transition-colors hover:text-foreground">{t.nav.portfolio}</Link>
            <Link href="/auto-trade" className="transition-colors hover:text-foreground">{t.nav.autoTrade}</Link>
          </nav>

          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            {/* Trạng thái máy chủ hiển thị công khai: người dùng biết ngay
                số liệu đang xem là thật hay chỉ là dữ liệu mẫu. */}
            <span className="inline-flex items-center gap-1.5">
              <span className={`h-2 w-2 rounded-full ${STATUS_COLOR[status]}`} aria-hidden />
              {t.status[status]}
            </span>
            <span>© {new Date().getFullYear()} ForecastAI</span>
          </div>
        </div>
      </div>
    </footer>
  )
}
