"use client"

/**
 * system-banners.tsx – Hai dải thông báo ở cấp toàn ứng dụng.
 *
 * 1. <DemoDataBanner />  — báo cho người dùng biết khi số liệu đang xem là dữ liệu mẫu.
 * 2. <DisclaimerBar />   — tuyên bố miễn trừ trách nhiệm, hiện ở các trang có
 *                          nội dung dễ bị hiểu nhầm thành khuyến nghị đầu tư.
 *
 * VÌ SAO CẦN
 *
 * Bản trước chỉ có một dòng chữ nhỏ ở footer: "Paper trading only. Not financial
 * advice." Gần như không ai cuộn xuống tới đó, và nó không xuất hiện đúng lúc —
 * tức là lúc người dùng đang nhìn vào một biểu đồ dự báo giá hoặc một nút bật
 * bot giao dịch. Checklist đồ án yêu cầu "ghi rõ disclaimer"; đặt nó ngay cạnh
 * nội dung liên quan mới thực sự đáp ứng được yêu cầu đó.
 */

import { useState } from "react"
import { AlertTriangle, Info, WifiOff, X } from "lucide-react"

import { cn } from "@/lib/utils"
import { useLangStore } from "@/lib/store"
import { useBackendStore } from "@/lib/use-backend-status"

// Các component này dùng bảng chữ cục bộ thay vì hệ thống i18n chung,
// để có thể thêm mới mà không phải sửa lib/i18n.ts (nơi đang được nhiều
// trang khác dùng chung — sửa ở đó rủi ro hơn nhiều).
const TEXT = {
  vi: {
    demoTitle: "Đang hiển thị dữ liệu mẫu",
    demoBody:
      "Không kết nối được máy chủ, nên các số liệu bên dưới là dữ liệu mẫu dùng để minh hoạ giao diện — không phải giá thị trường thật.",
    demoBodyWaking:
      "Máy chủ đang khởi động lại (gói miễn phí tự ngủ khi không có truy cập). Quá trình này mất khoảng 30-60 giây.",
    notConfiguredTitle: "Chưa cấu hình máy chủ",
    notConfiguredBody:
      "Biến NEXT_PUBLIC_API_URL chưa được thiết lập, nên toàn bộ số liệu đang là dữ liệu mẫu.",
    disclaimerShort: "Công cụ học thuật — không phải lời khuyên đầu tư",
    disclaimerLong:
      "Mọi dự báo và nhận định trên trang này do mô hình AI sinh ra phục vụ mục đích học tập và nghiên cứu. Giao dịch chỉ là mô phỏng, không dùng tiền thật. Đừng dùng nội dung ở đây làm cơ sở cho quyết định đầu tư.",
    dismiss: "Đóng",
  },
  en: {
    demoTitle: "Showing sample data",
    demoBody:
      "The server is unreachable, so the figures below are sample data used to illustrate the interface — not real market prices.",
    demoBodyWaking:
      "The server is waking up (the free tier sleeps when idle). This usually takes 30-60 seconds.",
    notConfiguredTitle: "Server not configured",
    notConfiguredBody:
      "NEXT_PUBLIC_API_URL is not set, so all figures shown are sample data.",
    disclaimerShort: "Academic tool — not investment advice",
    disclaimerLong:
      "All forecasts and analysis on this page are generated by AI models for educational and research purposes. Trading is simulated with no real money. Do not use this content as a basis for investment decisions.",
    dismiss: "Dismiss",
  },
} as const

function useText() {
  const lang = useLangStore((s) => s.lang)
  return TEXT[lang] ?? TEXT.vi
}

/* ══════════════════════════════════════════════════════════════════════════
   DẢI BÁO DỮ LIỆU MẪU
   ══════════════════════════════════════════════════════════════════════════ */

export function DemoDataBanner() {
  const t = useText()
  const status = useBackendStore((s) => s.status)
  const lastChecked = useBackendStore((s) => s.lastChecked)

  // "checking" là trạng thái bình thường lúc mới tải trang — không làm phiền
  // người dùng bằng một cảnh báo sẽ biến mất sau một giây.
  if (status === "online" || status === "checking") return null

  const isNotConfigured = status === "not-configured"
  // Nếu vừa mới phát hiện offline, nhiều khả năng service chỉ đang được đánh thức.
  const likelyWaking = !isNotConfigured && lastChecked !== null && Date.now() - lastChecked < 90_000

  return (
    <div
      role="status"
      aria-live="polite"
      className="border-b border-warning/30 bg-warning/10"
      data-print-hide
    >
      <div className="mx-auto flex max-w-[1600px] items-start gap-3 px-4 py-2.5 lg:px-6">
        <WifiOff className="mt-0.5 h-4 w-4 shrink-0 text-warning" aria-hidden />
        <p className="text-sm leading-relaxed text-card-foreground">
          <span className="font-semibold text-warning">
            {isNotConfigured ? t.notConfiguredTitle : t.demoTitle}
          </span>
          <span className="mx-1.5 text-muted-foreground">·</span>
          <span className="text-muted-foreground">
            {isNotConfigured ? t.notConfiguredBody : likelyWaking ? t.demoBodyWaking : t.demoBody}
          </span>
        </p>
      </div>
    </div>
  )
}

/* ══════════════════════════════════════════════════════════════════════════
   HUY HIỆU DỮ LIỆU MẪU (đặt cạnh từng khối số liệu)
   ══════════════════════════════════════════════════════════════════════════ */

export function DemoDataBadge({ className }: { className?: string }) {
  const t = useText()
  const status = useBackendStore((s) => s.status)

  if (status === "online" || status === "checking") return null

  return (
    <span
      className={cn("fa-badge border-warning/40 bg-warning/15 text-warning", className)}
      title={t.demoBody}
    >
      <AlertTriangle className="h-3 w-3" aria-hidden />
      {t.demoTitle}
    </span>
  )
}

/* ══════════════════════════════════════════════════════════════════════════
   TUYÊN BỐ MIỄN TRỪ TRÁCH NHIỆM
   ══════════════════════════════════════════════════════════════════════════ */

/**
 * Bản đầy đủ — dùng ở đầu các trang Dự báo, Nghiên cứu và Giao dịch tự động,
 * tức những nơi nội dung dễ bị đọc thành khuyến nghị mua bán.
 *
 * `dismissible` cho phép người dùng đóng lại trong phiên hiện tại. Trạng thái
 * này KHÔNG được lưu lâu dài — mỗi phiên làm việc mới, cảnh báo lại hiện.
 */
export function DisclaimerCard({
  dismissible = false,
  className,
}: {
  dismissible?: boolean
  className?: string
}) {
  const t = useText()
  const [dismissed, setDismissed] = useState(false)

  if (dismissed) return null

  return (
    <div
      role="note"
      className={cn(
        "relative flex items-start gap-3 rounded-lg border border-info/30 bg-info/10 p-3.5",
        className,
      )}
    >
      <Info className="mt-0.5 h-4 w-4 shrink-0 text-info" aria-hidden />
      <div className="min-w-0 flex-1">
        <p className="text-sm font-semibold text-card-foreground">{t.disclaimerShort}</p>
        <p className="mt-1 text-sm leading-relaxed text-muted-foreground">{t.disclaimerLong}</p>
      </div>
      {dismissible && (
        <button
          type="button"
          onClick={() => setDismissed(true)}
          aria-label={t.dismiss}
          className="shrink-0 rounded p-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
        >
          <X className="h-4 w-4" />
        </button>
      )}
    </div>
  )
}

/** Bản một dòng — dùng khi không gian hẹp, ví dụ dưới một biểu đồ. */
export function DisclaimerInline({ className }: { className?: string }) {
  const t = useText()
  return (
    <p className={cn("flex items-center gap-1.5 text-xs text-muted-foreground", className)}>
      <Info className="h-3 w-3 shrink-0" aria-hidden />
      {t.disclaimerShort}
    </p>
  )
}
